---
- hosts: all
  gather_facts: no

  tasks:
    - name: Enable Root Login
      become: true
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin yes"
        state: present
        backup: no
      notify:
        - restart ssh

  handlers:
    - name: restart ssh
      systemd:
        name: sshd
        state: restarted