---
- name: Install OpenJDK 8, 11, and 17
  hosts: all
  become: yes  # Run tasks with sudo

  vars:
    openjdk_version: "17"  # Set the desired OpenJDK version

  tasks:
    - name: Update package cache (Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update package cache (Alpine)
      apk:
        update_cache: yes
      when: ansible_os_family == "Alpine"

    - name: Add WTF repository and update cache (Debian - OpenJDK 8 only)
      block:
        - name: Download WTF repository source
          get_url:
            url: http://www.mirbsd.org/~tg/Debs/sources.txt/wtf-bookworm.sources
            dest: /etc/apt/sources.list.d/wtf-bookworm.sources

        - name: Update package cache
          apt:
            update_cache: yes
      when: openjdk_version == "8" and ansible_os_family == "Debian"

    - name: Add OpenJDK 8 repository (Debian)
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
        state: present
        filename: openjdk-8
        update_cache: yes
      when: openjdk_version == "8" and ansible_os_family == "Debian"

    - name: Install OpenJDK 8 (Debian)
      apt:
        name: openjdk-8-jdk
        state: present
      when: openjdk_version == "8" and ansible_os_family == "Debian"

    - name: Add OpenJDK 11 repository (Debian)
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }} main
        state: present
        filename: openjdk-11
        update_cache: yes
      when: openjdk_version == "11" and ansible_os_family == "Debian"

    - name: Install OpenJDK 11 (Debian)
      apt:
        name: openjdk-11-jdk
        state: present
      when: openjdk_version == "11" and ansible_os_family == "Debian"

    - name: Install OpenJDK 8 (Alpine)
      apk:
        name: openjdk8
        state: present
      when: openjdk_version == "8" and ansible_os_family == "Alpine"

    - name: Install OpenJDK 11 (Alpine)
      apk:
        name: openjdk11
        state: present
      when: openjdk_version == "11" and ansible_os_family == "Alpine"

    - name: Add OpenJDK 17 repository (Debian)
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }} main
        state: present
        filename: openjdk-17
        update_cache: yes
      when: ansible_distribution_release != "stretch" and ansible_os_family == "Debian"

    - name: Install OpenJDK 17 (Debian)
      apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_distribution_release != "stretch" and ansible_os_family == "Debian"

    - name: Install OpenJDK 17 (Alpine)
      apk:
        name: openjdk17
        state: present
      when: ansible_os_family == "Alpine"
