---
- name: Install Graylog Sidecar
  hosts: all
  become: yes

  vars:
    graylog_server_url: "http://logs.home.alvonellos.com:9000/api"
    graylog_server_api_token: "16cs4hi20rlft961obn2e18cj75fmhehmdvmhhn6dlkec3jfloes"
    local_destination_path: "/etc/graylog/sidecar/sidecar.yml"
    remote_source_path: "/etc/graylog/sidecar/sidecar.yml"
    remote_username: "root"
    remote_hostname: "cluster-node0"

  tasks:
    - name: Download and install Graylog Sidecar
      get_url:
        url: "https://github.com/Graylog2/collector-sidecar/releases/download/1.1.0/graylog-sidecar_1.1.0-1_amd64.deb"
        dest: "/root/graylog-sidecar.deb"
      when: ansible_distribution == "Ubuntu"

    - name: Download and install Graylog Sidecar
      get_url:
        url: "https://github.com/Graylog2/collector-sidecar/releases/download/1.1.0/graylog-sidecar-1.1.0-1.x86_64.rpm"
        dest: "/root/graylog-sidecar.rpm"
      when: ansible_distribution == "CentOS"

    - name: Install Graylog Sidecar package on Ubuntu
      apt:
        deb: "/root/graylog-sidecar.deb"
      when: ansible_distribution == "Ubuntu"

    - name: Install Graylog Sidecar package on CentOS
      yum:
        name: "/root/graylog-sidecar.rpm"
      when: ansible_distribution == "CentOS"

    - name: Add syslog forwarding configuration to rsyslog
      blockinfile:
        path: /etc/rsyslog.d/remote-logging.conf
        block: "*.* @logs.home.alvonellos.com:514;RSYSLOG_SyslogProtocol23Format"
        create: yes

    - name: Install Graylog Sidecar service
      command: "sudo graylog-sidecar -service install"

    - name: Create Graylog agent service file
      template:
        src: graylog.sidecar.yaml.j2
        dest: /etc/graylog/sidecar/sidecar.yml
      notify:
        - Restart Graylog Sidecar

  handlers:
    - name: Restart Graylog Sidecar
      systemd:
        name: graylog-sidecar
        state: restarted