---
- name: Install Graylog Sidecar
  hosts: your_graylog_sidecar_hosts
  become: yes

  vars:
    graylog_server_url: "http://logs.home.alvonellos.com:9000/api"
    graylog_server_api_token: "16cs4hi20rlft961obn2e18cj75fmhehmdvmhhn6dlkec3jfloes"

  tasks:
    - name: Download and install Graylog Sidecar
      get_url:
        url: "https://github.com/Graylog2/collector-sidecar/releases/download/1.1.0/graylog-sidecar_1.1.0-1_amd64.deb"
        dest: "/tmp/graylog-sidecar.deb"

    - name: Install Graylog Sidecar package
      apt:
        deb: "/tmp/graylog-sidecar.deb"
      when: ansible_distribution == "Ubuntu"

    - name: Install Graylog Sidecar package
      yum:
        name: "/tmp/graylog-sidecar.rpm"
      when: ansible_distribution == "CentOS"

    - name: Fetch Graylog Sidecar configuration
      hosts: your_graylog_sidecar_hosts
      become: yes

      tasks:
        - name: Fetch sidecar.yml from remote host
          command: scp root@pihole0.home.alvonellos.com:/etc/graylog/sidecar/sidecar.yml /etc/graylog/sidecar/sidecar.yml
          delegate_to: localhost

        - name: Copy the fetched file to the local machine
          fetch:
            src: /tmp/sidecar.yml
            dest: ./sidecar_configs/
            flat: yes


  handlers:
    - name: Restart Graylog Sidecar
      systemd:
        name: graylog-sidecar
        state: restarted

- name: Add syslog forwarding configuration to rsyslog
  hosts: your_target_hosts
  become: yes

  tasks:
    - name: Add syslog forwarding configuration to rsyslog
      lineinfile:
        path: /etc/rsyslog.conf
        line: "*.* @logs.home.alvonellos.com:514;RSYSLOG_SyslogProtocol23Format"
        insertbefore: EOF  # Insert before the EOF (end of file) marker
      notify:
        - Restart rsyslog

  handlers:
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted