---
- name: Install OpenJDK 8, 11, and 17
  hosts: all
  become: yes  # Run tasks with sudo

  vars:
    openjdk_version: "17"  # Set the desired OpenJDK version

  tasks:
    - name: Add OpenJDK 8 repository
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
        state: present
        filename: openjdk-8
        update_cache: yes
      when: ansible_distribution_release == "bookworm"  # Debian 9 (stretch)

    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present
      when: ansible_distribution_release == "bookworm"  # Debian 9 (stretch)

    - name: Add OpenJDK 11 repository
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }} main
        state: present
        filename: openjdk-11
        update_cache: yes
      when: ansible_distribution_release == "bookworm"  # Debian 10 (buster)

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_distribution_release == "bookworm"  # Debian 10 (buster)

    - name: Add OpenJDK 17 repository
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }} main
        state: present
        filename: openjdk-17
        update_cache: yes

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present
