---
- name: Install Graylog Sidecar
  hosts: all
  become: yes

  vars:
    graylog_server_url: "http://logs.home.alvonellos.com:9000/api"
    graylog_server_api_token: "16cs4hi20rlft961obn2e18cj75fmhehmdvmhhn6dlkec3jfloes"
  tasks:
    - name: Download and install Graylog Sidecar
      get_url:
        url: "wget https://packages.graylog2.org/repo/packages/graylog-sidecar-repository_1-5_all.deb"
        dest: "/root/graylog-sidecar.deb"
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Download and install Graylog Sidecar
      get_url:
        url: "https://packages.graylog2.org/repo/packages/graylog-sidecar-repository_1-5_all.deb"
        dest: "/root/graylog-sidecar.rpm"
      when: ansible_distribution == "CentOS"

    - name: Install Graylog Sidecar package on Ubuntu
      apt:
        deb: "/root/graylog-sidecar.deb"
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Install Graylog Sidecar package on CentOS
      yum:
        name: "/root/graylog-sidecar.rpm"
      when: ansible_distribution == "CentOS"

    - name: Install Graylog Sidecar service
      command: "sudo graylog-sidecar -service install"

    - name: Create Graylog agent service file
      template:
        src: graylog.sidecar.yaml.j2
        dest: /etc/graylog/sidecar/sidecar.yml
      notify:
        - Restart Graylog Sidecar

  handlers:
    - name: Restart Graylog Sidecar
      systemd:
        name: graylog-sidecar
        state: restarted