---
- name: update cluster
  hosts: cluster
  remote_user: root

  tasks:
    - name: Update and upgrade apt
      become: true
      apt:
        upgrade: yes
        update_cache: yes
  tasks:
    - name: Update and upgrade apt dist
      become: true
      apt:
        upgrade: dist
        update_cache: yes

    - name: Remove unused packages
      become: true
      apt:
        autoremove: yes

    - name: Clean up package cache
      become: true
      apt:
        autoclean: yes
